/** 8px-grid spacing rhythm for the Home screen — XS/SM/MD/LG/XL = 8/16/24/32/40. */
export const homeSpace = {
  xs: 8,
  sm: 16,
  md: 24,
  lg: 32,
  xl: 40,
} as const;

export const homeSpacing = {
  screenPadding: homeSpace.sm,
  screenBackground: "#FFFBF5",
  headerToStats: homeSpace.sm,
  headerTitleToSubtitle: homeSpace.xs - 2,
  headerTextToActions: homeSpace.xs,
  statsToContinue: homeSpace.md,
  continueToFocus: homeSpace.md,
  focusToRecommended: homeSpace.lg,
  recommendedToBottom: homeSpace.xl,
  sectionHeaderToCards: homeSpace.sm,
  statChipGap: homeSpace.xs,
  statChipPaddingH: homeSpace.sm,
  statChipPaddingV: homeSpace.xs,
  statStreakOffset: homeSpace.xs,
  focusCardGap: homeSpace.sm,
  focusStreamingCardGap: homeSpace.sm,
  focusStreamingCardHeight: 200,
  focusStreamingCardRadius: homeSpace.xs,
  focusStreamingCardPadding: homeSpace.sm,
  focusIconToText: homeSpace.sm,
  focusCategoryToTopic: 0,
  continueCardMinHeight: 168,
  continueContentPaddingTop: homeSpace.sm,
  continueContentPaddingBottom: homeSpace.sm,
  continueContentPaddingLeft: homeSpace.sm,
  continueContentPaddingRight: 112,
  continueTitleToSubtitle: homeSpace.xs,
  continueLanguageNameMarginTop: homeSpace.xs,
  continueButtonMarginLeft: homeSpace.sm,
  continueButtonMarginBottom: homeSpace.sm,
  continueButtonHeight: 48,
  vocabCardRadius: homeSpace.xs,
  vocabCardPadding: homeSpace.sm,
  vocabRowGap: homeSpace.xs,
  vocabRowRadius: homeSpace.sm,
  vocabRowPaddingV: homeSpace.sm,
  vocabRowPaddingH: homeSpace.sm,
  vocabDividerMarginH: homeSpace.sm,
  cardRadius: homeSpace.xs,
  statChipRadius: homeSpace.xs,
  notificationRadius: homeSpace.xs,
  notificationDotOffset: homeSpace.xs,
  focusCardWidth: 140,
  thumbnailSize: 88,
  playButtonSize: 32,
  actionButtonSize: 40,
  focusIconSize: 48,
  notificationButtonSize: 48,
  mascotWidth: 120,
  mascotOverlap: homeSpace.md,
  progressBarHeight: homeSpace.xs,
} as const;

export const HOME_CARD_SHADOW = {
  shadowColor: "#0d132b",
  shadowOffset: { width: 0, height: 1.5 },
  shadowOpacity: 0.2,
  shadowRadius: 2,
  elevation: 4,
} as const;

export const RECENT_VOCAB_SHADOW = {
  shadowColor: "#0d132b",
  shadowOffset: { width: 0, height: 1.5 },
  shadowOpacity: 0.1,
  shadowRadius: 2,
  elevation: 4,
} as const;
